---

- name: Create servers
  hosts: localhost
  vars_prompt:
    - name: key_name
      prompt: Key name?
      private: false
    - name: network
      prompt: Network?
      private: false
    - name: jumpHostIP
      prompt: Jump Host IP?
  roles:
    - instances
    - openstack_facts

- name: Configure VMs
  hosts: created_instances
  gather_facts: false
  become: true
  roles:
  - hosts
  - ocfs2
