---

- name: Create servers
  hosts: localhost
  vars_prompt:
    - name: key_name
      prompt: Key name?
      private: false
    - name: network
      prompt: Network?
      private: false
    - name: jumpHostIP
      prompt: Jump Host IP?
      private: false
    - name: jumpHostUser
      prompt: Jump Host user?
      default: almalinux
  tasks:
    - set_fact:
        network: "{{ network }}"
  roles:
    - role: instances
    - role: openstack_facts

- name: Configure VMs
  hosts: created_instances
  gather_facts: true
  become: true
  vars:
    network: "{{ hostvars['localhost']['network'] }}"
  roles:
    - role: hosts
    - role: ocfs2
      when: fs == 'ocfs2'
    - role: gfs2
      when: fs == 'gfs2'
