---

- name: Create servers
  hosts: localhost
  vars_prompt:
    - name: key_name
      prompt: Key name?
      private: false
      # default: <username> 
    - name: network
      prompt: Network?
      private: false
      # default: <project_XXXXXXX>
    - name: jumpHostIP
      prompt: Jump Host IP?
      # default: <IP>
    - name: jumpHostUser
      prompt: Jump Host user?
      default: almalinux
  roles:
    - role: instances
    - role: openstack_facts

- name: Configure VMs
  hosts: created_instances
  gather_facts: false
  become: true
  roles:
    - role: hosts
    - role: ocfs2
      when: fs == 'ocfs2'
    - role: gfs2
      when: fs == 'gfs2'
