
- name: Install modules and gfs2
  apt:
    update_cache: yes
    name:
      - gfs2-utils
      - dlm-controld
      - linux-modules-extra-{{ ansible_kernel }}

- name: Set Corosync log folder
  set_fact:
    corosync_log: /var/log/corosync
