
- name: Enable repositories
  community.general.dnf_config_manager:
    name:
    - highavailability
    - resilientstorage
    state: enabled

- name: Install packages
  dnf:
    name:
      - pacemaker
      - corosync
      - pcs
      - dlm
      - gfs2-utils

- name: Set Corosync log folder
  set_fact:
    corosync_log: /var/log/cluster
