
- name: Enable repositories
  community.general.dnf_config_manager:
    name:
    - highavailability
    - resilientstorage
    state: enabled

- name: Install packages
  dnf:
    name:
      - pacemaker
      - corosync
      - pcs
      - dlm
      - gfs2-utils
      - lvm2-lockd
      - fence-agents-openstack
      - pip

- name: Pip install
  ansible.builtin.pip:
    name:
      - python-openstackclient
      - python-novaclient